apiVersion: v1
kind: Pod
metadata:
  name: victim-PLACEHOLDER
  namespace: risk-demo
  labels:
    app: victim
spec:
  priorityClassName: PRIORITY_PLACEHOLDER
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.9
    resources:
      requests:
        cpu: CPU_REQ_PLACEHOLDER
        memory: MEM_REQ_PLACEHOLDER
      limits:
        cpu: CPU_LIM_PLACEHOLDER
        memory: MEM_LIM_PLACEHOLDER