apiVersion: v1
kind: Namespace
metadata:
  name: risk-demo-b
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-risk-demo-b
  namespace: risk-demo-b
spec:
  hard:
    requests.cpu: "3000m"
    limits.cpu: "4000m"
    requests.memory: "3Gi"
    limits.memory: "5Gi"
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-risk-demo-b-defaults
  namespace: risk-demo-b
spec:
  limits:
    - type: Container
      default:
        cpu: "300m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "256Mi"
      max:
        cpu: "4"
        memory: "4Gi"
      min:
        cpu: "50m"
        memory: "128Mi"
