## FAST TEMPLATE: Same stress pod; parameterized limits/requests.
apiVersion: v1
kind: Pod
metadata:
  name: stress-PLACEHOLDER
  labels:
    app: stress
spec:
  restartPolicy: Never
  containers:
  - name: stress
    image: polinux/stress-ng:latest
    args:
    - --cpu
    - "CPU_STRESS"
    - --vm
    - "VM_STRESS"
    - --vm-bytes
    - "VM_BYTES"
    resources:
      requests:
        cpu: CPU_REQ_STRESS
        memory: MEM_REQ_STRESS
      limits:
        cpu: CPU_LIM_STRESS
        memory: MEM_LIM_STRESS
